### ISSUE TITLE
Can't compile 4.0.0-rc4

### ISSUE THREAD

**Issue by rafaelrs** [haven-protocol-org/haven#4]
Operation performed on Ubuntu 16.04.5 LTS

I made everything according to README file, such as:

- Downloaded sources from https://github.com/haven-protocol-org/haven/archive/4.0.0-rc4.tar.gz and extracted it to my home.

- Install depencies (excluding Doxygen):

`sudo apt-get install build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libminiupnpc-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev libgtest-dev graphviz
`

- Started make:

`make release-static`

And after i got error, and i got errors:

ls: cannot access '.git/config': No such file or directory
/bin/sh: 1: git: not found
mkdir -p build/release
cd build/release && cmake -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=release ../.. && make
-- CMake version 3.5.1
-- Building without build tag
-- Could NOT find Git (missing:  GIT_EXECUTABLE) 
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled (using easylogging++)
-- Using OpenSSL include dir at /usr/include
-- Could NOT find HIDAPI (missing:  HIDAPI_LIBRARY HIDAPI_INCLUDE_DIR) 
-- Found miniupnpc API version 10
-- Using in-tree miniupnpc
CMake Error at external/CMakeLists.txt:41 (add_subdirectory):
  add_subdirectory given source "miniupnp/miniupnpc" which is not an existing
  directory.

CMake Error at external/CMakeLists.txt:42 (set_property):
  set_property could not find TARGET libminiupnpc-static.  Perhaps it has not
  yet been created.

CMake Error at external/CMakeLists.txt:46 (set_property):
  set_property could not find TARGET libminiupnpc-static.  Perhaps it has not
  yet been created.

-- Looking for libunbound
CMake Error at external/CMakeLists.txt:62 (add_subdirectory):
  The source directory

    /home/rafaelrs/Haven/haven-4.0.0-rc4/external/unbound

  does not contain a CMakeLists.txt file.

-- Using 64-bit LMDB from source tree
-- Could not find HIDAPI
-- Protobuf lib: /usr/lib/x86_64-linux-gnu/libprotobuf.a, inc: /usr/include, protoc: /usr/bin/protoc
CMake Warning at cmake/CheckTrezor.cmake:111 (message):
  Trezor protobuf messages could not be regenerated (err=1, python ).OUT: ,
  ERR: Traceback (most recent call last):

    File "tools/build_protob.py", line 16, in <module>
      + 'Use "git submodule update --init --recursive" to retrieve it.'

  ValueError: trezor-common submodule seems to be missing.

  Use "git submodule update --init --recursive" to retrieve it.

  .Please read src/device_trezor/trezor/tools/README.md
Call Stack (most recent call first):
  CMakeLists.txt:520 (include)

-- Building on x86_64 for x86-64
-- AES support enabled
-- Performing Test _fcf_protection=full_c
-- Performing Test _fcf_protection=full_c - Failed
-- Performing Test _fcf_protection=full_cxx
-- Performing Test _fcf_protection=full_cxx - Failed
-- Using C security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using C++ security hardening flags:  -Wformat -Wformat-security -fstack-protector -fstack-protector-strong
-- Using linker security hardening flags:  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack
-- Found Boost Version: 105800
-- Found readline library at: /usr
-- WARNING: Git was not found!
-- Trezor support disabled
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- GTest not found on the system: will use GTest bundled with this source
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/home/rafaelrs/Haven/haven-4.0.0-rc4/build/release/CMakeFiles/CMakeOutput.log".
See also "/home/rafaelrs/Haven/haven-4.0.0-rc4/build/release/CMakeFiles/CMakeError.log".
Makefile:94: recipe for target 'release-all' failed
make: *** [release-all] Error 1

[CMakeError.log](https://github.com/haven-protocol-org/haven/files/3262670/CMakeError.log)
[CMakeOutput.log](https://github.com/haven-protocol-org/haven/files/3262671/CMakeOutput.log)

**Comment by dweab** [comment]
Please use the latest tagged release
