### ISSUE TITLE
Payment error : "code":-4,"message":"failed to get output distribution"

### ISSUE THREAD

**Issue by bobbieltd** [haven-protocol-org/haven#7]
Ubuntu 18.04 - Intel Xeon - Compiled from source (Master brach)
I keep hitting my head wondering why no one has/report this problem like me. After fork, all transfers (both RPC and CLI) failed due to not be able to get output distribution. This issue is not new, I guess but it does not resolve with me after fork.
Rescan_bc, restoring wallets do not help.
Can you help ?

**Comment by goshiz** [comment]
This issue has been resolve in release v0.14.1

see https://github.com/haven-protocol-org/haven/releases/tag/v0.14.1-release

**Comment by fox4886** [comment]
Hello. Help to deal with the error: failed to get output distribution. I use haven-win-x64-v0. 14. 1-cli.zip.
